name: Digital Archive Builder
author: David Varghese
description: Action to build Quartz website using Markdown Files

inputs:
    MEASUREMENT_ID:
      description: Token to link site with Google Analytics Property
      required: true

runs:
    using: composite
    steps:
        - name: Copy Markdown Files
          id: copy-markdown
          shell: bash
          run: |
              cp -a ${{ env.FILES_PATH }}/MainVault/. ${{ env.SITE_PATH }}/content \
              && rm -rf ${{ env.SITE_PATH }}/content/{read-and-watch-list,.gitkeep}
        - name: Copy Config
          id: copy-config
          shell: bash
          run: cp -a ${{ env.FILES_PATH }}/config/. ${{ env.SITE_PATH }}
        - name: Run Script
          id: run-script
          shell: bash
          run: node ${{ env.SITE_PATH }}/scripts/modifyIndex.cjs ${{ env.SITE_PATH }}/content/index.md
        - name: Setup Google Analytics
          id: setup-analytics
          shell: bash
          run:  sed -i -E "s/XXXXXX/${{ inputs.MEASUREMENT_ID }}/" ${{ env.SITE_PATH }}/quartz.config.ts 
        - name: Install Dependencies
          id: install-dependencies
          shell: bash
          run: |
              cd ${{ env.SITE_PATH }} \
              && npm clean-install \
              && npm install rehype-external-links
        - name: Build Site
          id: build-site
          shell: bash
          run: |
            cd ${{ env.SITE_PATH }} \
            && npx quartz build
