name: Digital Archive Builder
author: David Varghese
description: Action to build Quartz website using Markdown Files

inputs:
    MEASUREMENT_ID:
      description: Token to link site with Google Analytics Property
      required: true

runs:
    using: composite
    steps:
        - name: Copy Markdown Files
          id: copy-markdown
          shell: bash
          run: |
              cp -a source/MainVault/. quartz/content \
              && rm -rf quartz/content/{read-and-watch-list,us-court-system,.gitkeep}
        - name: Copy Config
          id: copy-config
          shell: bash
          run: cp -a source/config/. quartz
        - name: Run Script
          id: run-script
          shell: bash
          run: node quartz/scripts/modifyIndex.cjs quartz/content/index.md
        - name: Setup Google Analytics
          id: setup-analytics
          shell: bash
          run:  sed -i -E "s/XXXXXX/${{ inputs.MEASUREMENT_ID }}/" quartz/quartz.config.ts 
        - name: Install Dependencies
          id: install-dependencies
          shell: bash
          run: |
              cd quartz \
              && npm clean-install \
              && npm install rehype-external-links
        - name: Build Site
          id: build-site
          shell: bash
          run: |
            cd quartz \
            && npx quartz build
