name: 'Deploy Notes to Netlify'
on:
  push:
    branches: [ main ]

jobs:
  mkdocs-notes:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build and Deploy Site'
        id: mkdocs-build
        uses: dvdmtw98/mkdocs-netlify-deploy@main
        with:
          build_mode: manual
          main_repository: dvdmtw98/notes
          config_repository: dvdmtw98/website-config
          markdown_location: My Vault
          assets_location: notes-config/assets
          hooks_location: common/hooks
          config_location: notes-config
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}