name: Deploy Digital Archive to Netlify
run-name: Deploy to Netlify by @${{ github.actor }}

on:
    push:
        branches: [main]
        paths-ignore:
            - "notes-vault/.obsidian/**"

jobs:
    digital-archive:
        name: Digital Archive Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Quartz
              id: checkout-quartz
              uses: actions/checkout@v4
              with:
                  repository: jackyzha0/quartz 
                  ref: v4.2.4
                  path: quartz
            - name: Checkout Repository
              id: checkout-repository
              uses: actions/checkout@v4
              with:
                  submodules: true
                  path: source
            - name: Build Digital Archive
              id: build-digital-archive
              uses: ./source/.github/actions
              with:
                  MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
            - name: Netlify Deploy
              id: netlify-deploy
              uses: jsmrcaga/action-netlify-deploy@v2.2.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: GitHub Action Deployment
                  NETLIFY_DEPLOY_TO_PROD: true
                  install_command: echo Skipping...Install not required
                  build_command: echo Skipping...Build not required
                  build_directory: quartz/public
